name: Shedule Netlify Build
on:
  schedule:
    - cron: '21 21 * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/603ffcef717c1c008513673c
